### ISSUE TITLE
Underscores in optional parameters

### ISSUE THREAD

**Issue by flusflas** [moigagoo/cliar#11]
Hi, I'm testing Cliar and it seems awesome! I'm trying to use an optional parameter with underscores in its name, but it looks Cliar is failing because of the '_' to '-' replacement (or maybe I'm misusing it). It's working for positional arguments, but not for optional ones. I'm using Python 3.7.4.

Example:
``` python3
from cliar import Cliar, set_help

class Calculator(Cliar):
    """ Calculator app. """

    @set_help({'number_x': 'Number X', 'number_y': 'Number Y'})
    def add(self, number_x: float, number_y: float = 0):
        """ Add two numbers. """

        print(f'The sum of {number_x} and {number_y} is {number_x+number_y}.')


if __name__ == '__main__':
    Calculator().parse()
```

Output:
``` console
$ python cli.py add 1 --number-y 1
Traceback (most recent call last):
  File "cli.py", line 31, in <module>
    Calculator().parse()
  File "/.../lib/python3.7/site-packages/cliar/cliar.py", line 280, in parse
    command_args = {arg: vars(args)[arg] for arg in command.args}
  File "/.../lib/python3.7/site-packages/cliar/cliar.py", line 280, in <dictcomp>
    command_args = {arg: vars(args)[arg] for arg in command.args}
KeyError: 'number-y'
```

Thanks!

**Comment by moigagoo** [comment]
Thanks fo using Cliar and for the kind words! Just pushed version 1.3.3 with the fix to PyPI. Enjoy!
